pyeve/eve

- MANIFEST.in
- setup.py
Additionally, README.rst has been added to MANIFEST.in
> fix nicolaiarocci/eve#540

- AUTHORS
- docs/config.rst
- eve/default_settings.py
- eve/render.py
- eve/tests/renders.py
> Cors allow credentials

- eve/methods/common.py
> Specify filename keyword arg in store_media_files

- docs/snippets/hooks_blueprints.rst
- docs/snippets/index.rst
Just a new snippet to handle Eve hooks from our blueprints.
> Snippets, hooks from blueprints

- eve/methods/common.py
- eve/tests/methods/common.py
> Fix serialization for lists of lists

- docs/tutorials/account_management.rst
2 equal symbol in page http://python-eve.org/tutorials/account_management.html are wrong
> condition symbol

- docs/tutorials/account_management.rst
quote around extra_response_fields
> quote around extra_response_fields in doc

- eve/flaskapp.py
- eve/tests/methods/post.py
- eve/tests/test_settings.py
Fix for https://github.com/nicolaiarocci/eve/issues/636
> Fix projection

- docs/features.rst
> Update soft delete docs to better explain restoring documents

- eve/io/mongo/mongo.py
- eve/tests/config.py
`create_index` currently add indexes only for the resource but we also require indexes on the resource`_versions` which is created if versioning is enabled.
> create_index add indexes to the versions collection

- eve/methods/common.py
- eve/tests/methods/get.py
We use it for returning in  a single call entities from multiple resources
> Feature: add the ability to customize the returned HATEOAS links

- docs/features.rst
- eve/methods/common.py
- eve/tests/methods/get.py
- eve/tests/test_settings.py
So far it was only possible to embed list, with this patch it's now
possible to embed directly a given resource.
The patch also breaks the maximum number of level of embedded resources.
> Add the ability to embed ObjectId directly

- eve/versioning.py
Improves versioned document GET performance at load and for large documents.
Deep copies are very expensive, and not actually required when synthesizing a document version.
> Build specific versions without deepcopying root document. 

- docs/rest_api_for_humans.rst
> Spelling Fix in rest_api_for_humans.rst

- eve/methods/common.py
Also standardizes value serialization exception handling across the serialize function.
An [earlier commit](https://github.com/nicolaiarocci/eve/commit/347cee6c588185119a2f3172123a1848faf1af24) added a new serializer for values of field type `number` which parsed the values as JSON strings in order to support `x-www-urlencode` requests. However, those values are not strings when submitted in more typical `application/json` requests. The parsing should only happen when the given value is a string.
Attempting to parse actual numbers throws an exception which was sometimes caught by a try/except block around the serializer call, but that exception handling only wrapped one possible serializer call. When submitting more complex schema that hit other serializer calls, a list of numbers for …
> Don't attempt to parse number values as strings when they are numerical.

- eve/methods/delete.py
If #814 is confirmed, here is a starting proposal
Signed-off-by: cbonnard <cyril.bonnard>
> Fix issue #814

- eve/auth.py
- eve/tests/auth.py
Add support for bearer tokens to auth module.
Fixes #866
> Handle authorization bearer tokens

- docs/index.rst
> Clarify Redis is an optional dependency.

- docs/config.rst
- eve/default_settings.py
- eve/flaskapp.py
- eve/tests/config.py
- Test for MONGO_OPTIONS config settings (both for app and resource)
-  Flask-PyMongo compatibility for MONGO_CONNECT config setting.
https://flask-pymongo.readthedocs.io/en/latest/#configuration
https://api.mongodb.com/python/current/faq.html#multiprocessing
> Test for MONGO_OPTIONS config  & Flask-PyMongo compatibility for MONGO_CONNECT setting

- eve/tests/versioning.py
> Fixed test

- eve/versioning.py
This patch is a proposed fix for #967.
> Fix to push auth_field onto versioned documents

- .travis.yml
- CHANGES
- docs/config.rst
- docs/validation.rst
- eve/io/mongo/mongo.py
- eve/io/mongo/validation.py
- eve/tests/io/mongo.py
- eve/tests/methods/common.py
- eve/tests/methods/post.py
- eve/tests/test_settings.py
- requirements.txt
- setup.py
This PR will provide support for mongodb decimal data type: #1045.
> Support Decimal type MongoDB

- eve/io/mongo/mongo.py
> Issue-1181: Added support $centerSphere operator

- eve/default_settings.py
- eve/methods/common.py
- eve/tests/__init__.py
- eve/tests/auth.py
- eve/tests/config.py
- eve/tests/endpoints.py
- eve/tests/methods/get.py
- eve/tests/methods/patch.py
- eve/tests/methods/post.py
- eve/tests/methods/put.py
- eve/tests/methods/ratelimit.py
- eve/tests/renders.py
- eve/tests/versioning.py
> Add JSON response for rate limit exceeded scenario

- eve/io/mongo/media.py
Hi!
Do you think any tests needed for this fix?
> Instantiate GridFS object with 'disable_md5=True' (fix #1410)

- eve/io/mongo/validation.py
- eve/tests/methods/post.py
- eve/tests/test_settings.py
> Fix unique field query construction when field is nested

- eve/methods/common.py
- eve/methods/delete.py
- eve/methods/patch.py
- eve/methods/post.py
- eve/methods/put.py
> Fix _update field missing timezone

- eve/methods/common.py
- tests/__init__.py
- tests/methods/delete.py
- tests/methods/get.py
- tests/versioning.py
> Caches `field_definition` calls to improve `build_response_document` performance
