eve/methods/common.py, eve/tests/methods/get.py
I've run into a bug when a get request is done with a embedded params on a missing subdocument
Considering a request `GET http://api.lvh.me:8080/elements?projection={"tests.test": 1}`
If the `elements` collection contains an element which doesn't have a `tests` entry, the request is going to crash leading to a 500 response.
=> Fix bug when embedded is used on subdocument with missing field

eve/io/mongo/validation.py, eve/tests/io/mongo.py
Hi,
I've found initializing mongo's Validator with `transparent_schema_rules=True` is  quite error-prone
For exemple considering a schema with a typo (`child_field` not enclosed in `{'type': 'dict', 'schema': {...}}`):
```
{
'field': {
'type': 'list',
'schema': {
'child_field': {'type': 'string'}
}
}
}
```
With `transparent_schema_rules=True` this schema is considered as valid and any arbitrary payload will be silently accepted !
This fix remove the need to use `transparent_schema_rules=True`... and fix a unittest whose invalid schema were silently failing, ouch ! ;-)
=> Fix mongo Validator to work without transparent_schema_rules=True

AUTHORS, eve/io/mongo/geo.py, eve/tests/io/mongo.py
See #591 
Fixed by adding new test and allowing for integers in the validation typecheck.
One minor caveat is that integers will also be stored as integers and as such a different type in mongo.
However, querying still works fine. See screenshot below.
=> Geopoint decimal fix

eve/methods/patch.py, eve/tests/methods/patch.py
so that `on_update` and `on_updated` callbacks will get
same values
fix #611
=> make sure original is not modified during patch

eve/io/media.py, eve/io/mongo/media.py, eve/io/mongo/mongo.py, eve/methods/common.py, eve/methods/delete.py, eve/tests/io/media.py
Fix for https://github.com/nicolaiarocci/eve/issues/632
The only existing dependency is on the app.config, this shouldn't be a problem in most of the cases.
For Celery, we just add the Eve app config to Celery app config.
=> Remove dependency on the Flask request in Mongo datalayer

AUTHORS, eve/default_settings.py, eve/methods/common.py, eve/tests/io/media.py
Allows media urls to use a custom URL as a base pattern.
When 'RETURN_MEDIA_AS_URL' is set to True and 'MEDIA_CUSTOM_URL' is not None, any media files
in a collection will return a concatenation of this setting plus the file ID.
This allows custom 'MediaStorage' to be much more flexible.
=> Added 'MEDIA_CUSTOM_URL' setting for #639

eve/methods/common.py
This PR fix an issue with `post_internal` when the `_id` field is specified in the posted document and the current request has its own `_id` parameter. The `_id` field of the posted document get replaced by the `_id` parameter of the current request.
This fix does only hide the real issue though. The use of `request.view_args` in `resolve_sub_resource_path` doesn't play well with `*_internal` methods as it tries to alter the document with data coming from the current request which may have no link with the `*_internal` request.
I guess a stronger fix would be to pass the route's parameters as an argument to the `*_internal` methods.
=> Do not overwrite the _id field as it is not a sub resource

eve/methods/get.py, eve/versioning.py
Synthesizing a specific document version in GET requests uses two `deepcopy` calls, but only one is necessary if `get_old_document` does not edit the document passed to it. Improves performance for large documents.
=> Improve performance of GET requests to versioned resources

eve/methods/get.py, eve/tests/versioning.py
GET fails if you change the _version to some other field name.
=> Using constant VERSION instead of hard coded '_version'

eve/tests/methods/patch.py, eve/tests/methods/put.py, eve/tests/test_settings.py
I'm trying to use new Cerberus' `dependencies` with value deps, and I can't make it to fail when the dependency is not met.
I've pushed some failing test to demonstrate my issue. Did I miss something?
=> Add some tests to demonstrate how dependencies with values doesn't work with patch and put

eve/methods/common.py
embedded_fields may point on a field that come from another embedded
document. For example, ['a.b.c', 'a.b', 'a']
The strategy is to sort out the different embedded_fields depending on
their number of '.'. This way, the ones with the greatest depth level
come last.
Combined with https://github.com/RedTurtle/eve-sqlalchemy/pull/47 it's
now possible to do include multi-level embedded resource with Eve-SQLAlchemy.
=> embedded documents following depth level

eve/tests/methods/post.py
If a field has both a dependency and a required directive, the required directive is just ignored. This PR contains a failing test to demonstrate the issue.
=> Dependency doesn't play well with required

docs/config.rst
I was wondering where was the PUT verb in your Resources or Item methods, until I tried some code samples and I just saw that you correctly accept PUT in item_methods but the docs do not accurately reflect that.
=> Added PUT to item_methods config docs

eve/io/mongo/mongo.py
Mongo layer should not depend on request context if possible, resource can be passed as a parameter.
=> Fix resource discovery in Mongo layer

eve/methods/patch.py, eve/methods/post.py, eve/methods/put.py, eve/tests/methods/patch.py, eve/tests/methods/post.py, eve/tests/methods/put.py
As far as I understood type coercion correctly, a successfully validated document should show the coerced values instead of the original ones. This commit changes Eve's behaviour regarding type coercion so coerced values get applied before the document is inserted or updated.
=> Apply Cerberus' type coercion to documents

docs/features.rst
Found a broken link in the docs...
=> Fix link to Mongo's "capped collections" doc

eve/io/mongo/validation.py
Found a couple of leftover references to `resource` within `_validate_data_relation`.
=> Remove 'resource' in _validate_data_relation docstring

tox.ini
There's an assignment of 'basestring' for to compatibility of both
python 2 and python 3. This causes flake8 to fail when executed with python 3
due to an unknown name.
This commit configures tox to run flake8 with python 2 even on systems
were python 3 is the default, to avoid problems here.
=> Use python 2 for flake8-tests

AUTHORS, eve/methods/get.py, eve/tests/__init__.py, eve/tests/methods/get.py, eve/utils.py
Parameters not recognised by Eve are stripped from HATEOAS URLs.
This change adds those parameters to HATEOAS URLs.
E.g.: I want to implement a different way of filtering content,
instead of using where:
?start_date=2014-01-25&search_for=foo
=> Allow other parameters to be part of urls

eve/methods/common.py, eve/tests/methods/common.py
On a side note, given the strong contract that this PR enforces, the null guards in the serializers could (and should, IMHO) be removed.
=> Skip any null value from attempting serialization (Fixes #772)

docs/features.rst
Same fix as https://github.com/nicolaiarocci/eve/pull/781
=> Fix typo in document embedding limitations example

eve/methods/get.py, eve/tests/methods/get.py, eve/tests/versioning.py, eve/utils.py
- Support weak ETags, commonly applied by servers transmitting gzipped content.
- Allow old versions to be cache validated using ETags.
Without 'If-None-Match' style cache validation supported, data migrations
that update old versions and correctly compute new ETags, but don't change
updated_at dates, will appear to be valid in client caches even though the
data has been changed.
=> Support etag cache validation for versioned documents 

AUTHORS, CHANGES, docs/config.rst, docs/features.rst, eve/default_settings.py, eve/methods/common.py, eve/tests/methods/delete.py, eve/tests/methods/patch.py, eve/tests/methods/put.py
If `ENFORCE_IF_MATCH` is disabled and `IF_MATCH` is enabled, then
the client can choose whether to provide the `If-Match` header in
its request. When `If-Match` is provided, then the request is treated as
conditional, meaning the ETag must match. When `If-Match` is absent,
then the ETag check is not enforced.
The `ENFORCE_IF_MATCH` flag defaults to `True`
Closes #657
=> Support ENFORCE_IF_MATCH flag

AUTHORS, eve/io/mongo/mongo.py, eve/tests/__init__.py, eve/tests/io/multi_mongo.py
Importing Flask extensions vie `flask.ext` is deprecated.
Close #898.
=> Import PyMongo Flask extension directly

eve/io/mongo/mongo.py, eve/tests/methods/common.py
A range of values is now serialized to boolean, namely:
0, 1, '0', '1', 'false', 'False', 'true', 'True'
This covers the most common boolean inputs.
Closes #947
=> Added serialization rule for boolean

eve/io/mongo/mongo.py
Fix bug that occured when (trying to) modify the _id of object.
Used to give a warning, now gives internal error because the mongodb version is not in the list above.
=> Current stable mongodb version is 3.4

eve/methods/common.py
Using global configuration ```OPLOG=True```, resource definition ```'internal_resource': True``` and then performing an \*_internal (* methods defined in OPLOG_METHODS) will trigger a keyerror in ```oplog_push``` entry update since the internal resource is not in config.URLS ```'r': config.URLS[resource]``` (tested 0.7.1 and 0.7.2)
Changing the  check in oplog_push:
```if not config.OPLOG or op not in config.OPLOG_METHODS:``` 
to
```if not config.OPLOG or op not in config.OPLOG_METHODS or resource not in config.URLS:```
should make sense
=> Internal resource, oplog enabled and *_internal raises keyerror

AUTHORS, eve/methods/common.py, eve/tests/methods/common.py
The purpose of this PR is to make sure all of the fields are correctly serialized when there are ```x_of``` validation rules.
The tricky part of this bug is that it is not stably repeatable. This is because the serialization iterates through the json keys in random order, and the bug shows up only when the fields that contain ```x_of``` rules are processed **before** other fields. In short, the ```schema``` variable in function ```serialize``` will be overwritten mistakenly in ```if x_of``` clause, causing the serialization of the rest of the fields are skipped, due to the ill-formed ```schema```.
Along with this bug fix, the PR also enabled correct serialization under circumstances where ```x_of``` appears at the first level of a field's schema whose type is list.
Two new unit test cases …
=> Fix a serialization bug that randomly skips fields if "x_of" is encountered

AUTHORS, eve/render.py, eve/tests/methods/common.py, py26-requirements.txt, requirements.txt, setup.py
It is unnecessary to require the ordereddict module because the backport_collections module already has the OrderedDict class.  This change removes the ordereddict dependency, and also ensures that backport_collections is only required when needed.
=> use OrderedDict from backport_collections

AUTHORS, docs/config.rst, eve/tests/methods/get.py, eve/tests/test_settings.py, eve/utils.py
This PR fixes issue #1123 
Also, commit bae6757 fixes the behavior of `ALLOWED_FILTERS` (and the related resource-specific `allowed_fillters`) settings in the same scenario as the one defined in #1123, i.e. filtering on a sub-document field.
=> 1123 sub document validate filters

eve/io/base.py, eve/io/mongo/mongo.py, eve/methods/common.py, eve/methods/put.py, eve/tests/auth.py
This PR fixes the behavior of PUT requests when User-Restricted Resource Access is enabled.
More in particular it ensures that, under every circumstance, users are unable to overwrite items owned by other users.
=> Fix PUT behavior with User-Restricted Resource Access

eve/methods/get.py, eve/tests/auth.py, eve/tests/io/multi_mongo.py
=> use simplejson module everywhere

eve/io/mongo/mongo.py, eve/methods/patch.py, eve/tests/methods/patch_atomic_concurrency.py
Atomic Concurrency Checks
See pyeve/eve#1231 for summary
Atomic Concurrency Checks
Prior to commit 54fd697 from 2016-November, ETags would be verified
twice during a patch. One ETag check would be non-atomic by Eve,
then again atomically by MongoDB during app.data.update(filter).
The atomic ETag check was removed during issue #920 in 54fd697
When running Eve in a scale-out environment (multiple processes),
concurrent simultaneous updates are sometimes allowed, because
the Python-only ETag check is not atomic.
There is a critical section in patch_internal() between get_document()
and app.data.update() where a competing Eve process can change the
document and ETag.
The included test simulates another process changing data & ETag
during the critical section. The test patches get_document() …
=> Atomic Concurrency Checks

docs/config.rst
=> docs, not valid python

eve/io/mongo/mongo.py
Closes #1216 
According to the MongoDB Manual https://docs.mongodb.com/manual/reference/database-references/#dbrefs DBRef documents resemble the following format { "**$ref**" : <value>, "$id" : <value>, "$db" : <value> }
Currently Eve conforms to that format only when processing a GET request. In PUT request, it will use { "**$col**" : <value>, "$id" : <value> }. The client needs to perform additional handling to convert data before a PUT request.
In this PR PUT request supports { "**$ref**" : <value>, "$id" : <value> } which is consistent with GET response. It is also backward compatible with the old { "**$col**" : <value>, "$id" : <value> } way.
=> Fix inconsistent DBRef format between GET and PUT

eve/endpoints.py
Currently, there is an issue with `abort(401)`. Per default,the keyword argument `www_authenticate` is `None` for the `UnauthorizedException`, i.e. `abort(401)` (as described in the [Werkzeug docs](https://werkzeug.palletsprojects.com/en/0.15.x/exceptions/#error-classes)), and the resulting exception attribute is `e.www-authenticate = (None,)`.
In [endpoints.py#L173](https://github.com/pyeve/eve/blob/master/eve/endpoints.py#L173), this `(None,)` is added to the header stack, which crashes response processing in [render.py#L164](https://github.com/pyeve/eve/blob/master/eve/render.py#L164), as `(None,)` cannot be unpacked to `header, value`.
In our API, an automated basic auth response does not make sense, yet calling `abort(401)` (without the `www_authenticate`) is currently impossible …
=> Do not crash without www-authentication header

eve/methods/get.py, eve/tests/methods/get.py
the count returned by `app.find` might be None if the count is disabled.
Later in get_internal, the HEADER_TOTAL_COUNT is prepared if the count
is enabled.
This commit fixes a bug that filtered out the HEADER_TOTAL_COUNT when
the resource is empty and the count is 0 because the check is done with a truthy condition. This truthy
condition has been replaced by an explicit `is not None` condition.
Fixes #1279
=> Fix HEADER_TOTAL_COUNT on emtpy resources

eve/tests/__init__.py, eve/tests/methods/patch.py, eve/tests/methods/post.py, eve/tests/methods/put.py, eve/tests/test_settings.py, eve/tests/versioning.py, eve/validation.py
* Refactor of "contacts" test data so it honours the fields that should have defaults when created
* Added a new fields in "contacts" schema to be able to properly refactor tests related to default values
* Added tests to cover several scenarios where default values are involved
=> Fixes behaviour of PUT requests not setting default values of fields.

docs/config.rst, eve/io/mongo/validation.py, eve/tests/methods/post.py, eve/tests/test_settings.py
Add new validation rule `unique_within_resource`.
This new validation rule enforces the uniqueness of an attribute only at API resource level, contrasting with the `unique` rule that enforces uniqueness at database collection level.
Fixes #1291
=> Add "unique_within_resource" validation rule

docs/features.rst
`curl` commands for the projection feature docs are incorrect, this merge request updates them.
Closes #1298 
The output of both commands on the public demo api.
```bash
$ curl -i -G http://eve-demo.herokuapp.com/people --data-urlencode 'projection={"lastname": 1, "born": 1}'
HTTP/1.1 200 OK
Content-Type: application/json
Content-Length: 2364
X-Total-Count: 7
Cache-Control: max-age=20
Expires: Mon, 16 Sep 2019 14:33:23 GMT
Last-Modified: Fri, 13 Sep 2019 08:34:26 GMT
Server: Eve/0.8 Werkzeug/0.14.1 Python/3.6.5
Date: Mon, 16 Sep 2019 14:33:03 GMT
X-Cache: MISS from w4m-mmm-almada-1
X-Cache-Lookup: HIT from w4m-mmm-almada-1:0
Via: 1.1 vegur, 1.1 w4m-mmm-almada-1 (squid/3.5.12)
Connection: keep-alive
{"_items": [{"_id": "5d70994dec8f9500043e5fe3", "lastname": "Red", "born": "Sun, 20 Jul …
```
=> docs: fix projection curl commands (#1298)

README.rst
Minor update to the README, just noticed while browsing.
Current URL (http://python-eve.org/funding):
Updated URL (http://python-eve.org/funding.html):
=> Update README funding URL

eve/flaskapp.py, eve/methods/delete.py, eve/methods/get.py, eve/methods/post.py, eve/methods/put.py, eve/tests/__init__.py
- fixed the 401 or 405 assertion always returning True
- tests were failing on a fresh install without test_user
- I made it a bit more pythonic.
=> Some minor style improvements and 2 test fixes

eve/io/mongo/mongo.py, eve/tests/__init__.py, eve/tests/methods/get.py, eve/tests/test_settings.py
Addresses #1345 
The Test Widget manufacturer now uses Mongo, so the SKUs resemble ObjectIds. Added a failing test to show why this is a problem. Fix the problem.
=> Always coerce id fields when performing mongotize even if query_objectid_as_string is on.

eve/default_settings.py, eve/tests/config.py
This isn't actually an error the Eve Framework will ever raise. As far
as I could tell.
However, separation between authentication and authorization is a must
even for less complex applicatons. 403 is the most adequate response a
server can provide to client whose authentication was accepted, yet for
some reason or another the server will not comply with the request.
The Eve Framework documentation suggests the usage of 403 in, at least
two instances:
* `abort(403)` in: https://docs.python-eve.org/en/stable/features.html#database-event-hooks
* The actual documentation for the `STANDARD_ERRORS` config variable,
describes 403 as a supported code, in: https://docs.python-eve.org/en/stable/config.html#global-configuration
=> Add 403 Forbidden to STANDARD_ERRORS

docs/config.rst, eve/io/mongo/validation.py, eve/tests/methods/post.py, eve/tests/test_settings.py
#1292 didn't contemplate the use of this new rule on resources that don't need it (but might use it). This PR fixes the issue.
=> Fix unique_within_resource rule used in resources without datasource filter

eve/methods/patch.py
=> fix versioning on PATCH when `merge_nested_documents` is disabled

eve/methods/common.py
I think there is a missed part in the condition for projection.
I've added a projection flag from the resource.
=> Add missed condition when projection is disabled per domain

eve/methods/common.py, eve/methods/patch.py
This is so users can control ReadPreference and WriteConcern. This should address #1411
=> Allow mongo_options to be passed to post, patch, and get_document.

eve/io/base.py, eve/io/mongo/mongo.py, eve/methods/common.py, eve/methods/patch.py, eve/tests/methods/patch.py
This is done by passing the options directly into the `eve.Mongo` `find_one` method.
The work doesn't cover adding arguments to find_one_raw or find since
they aren't needed to fix the bug.
I explored adding a fluid type interface for with_optios to the eve
PyMongos/Mongo/DataLayer classes but it was really clunky and I'd be
worried that such a fundamental change wouldn't be appropriate here.
=> Fix the mongo_options work by passing the options into find_one

docs/features.rst
inside example section of insert events, corrected the variable name in 'before_insert' function
=> corrected variable name

.travis.yml, AUTHORS, CHANGES.rst, setup.py, tox.ini
Hi @nicolaiarocci, would you consider dropping support for Python 2.7 and 3.5 (after EOL)?
=> Add Python 3.9 support

.travis.yml, CHANGES.rst, setup.py, tox.ini
As discussed in #1437, drop Python 3.5 support (and looking forward to dropping 2.7).
And update pypy3 to the latest version in travis.
How about adding GitHub Actions CI?
=> Drop Python 3.5 support and update pypy3 version

eve/io/mongo/geo.py, eve/methods/get.py
Two independent commits:
- `from __future__ import division` and then apply it to two integers where `a / b` returns a float
- simplify multiple `isinstance` calls
=> Prepare for Python3

CONTRIBUTING.rst
The fork link was pointing to the Flask repo.
=> Fix fork link in contributing info

docs/config.rst
`VALIDATION_ERROR_AS_STRING` doesn't exist in the source code so set it to `True` won't have any effect.
It must be `VALIDATION_ERROR_AS_LIST` instead.
=> Fix typo in config

docs/tutorials/account_management.rst, eve/methods/delete.py, eve/tests/config.py, eve/tests/methods/patch.py, eve/tests/methods/post.py
There are small typos in:
- docs/tutorials/account_management.rst
- eve/methods/delete.py
- eve/tests/config.py
- eve/tests/methods/patch.py
- eve/tests/methods/post.py
Fixes:
- Should read `occurrence` rather than `occurence`.
- Should read `existence` rather than `existance`.
- Should read `enabled` rather than `eanbled`.
- Should read `default` rather than `defult`.
- Should read `devolution` rather than `develtion`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: Fix a few typos

eve/utils.py
This solution seems to fit the current code best, but alternatively one could get the value earlier and return  `UuidRepresentation.STANDARD` early if the value is of a non-string type.
This PR is a fix to [issue #1486](https://github.com/pyeve/eve/issues/1486)
=> Fix issue  #1486

eve/methods/common.py, tox.ini
Fixes deprecation warnings in Python 3.12
=> datetime.utcnow -> datetime.now(UTC)
